ALTER TABLE member ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE member ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE member ADD COLUMN IF NOT EXISTS created_by VARCHAR(120);
ALTER TABLE member ADD COLUMN IF NOT EXISTS updated_by VARCHAR(120);
ALTER TABLE member ADD CONSTRAINT uq_member_mobile UNIQUE (mobile_no);
ALTER TABLE donation ADD COLUMN IF NOT EXISTS updated_by VARCHAR(120);
ALTER TABLE donation ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
